language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
  - pipenv install idna-ssl
# command to run the dependencies
script:
  - pipenv run tests
